use_frameworks!

platform :ios, '10.0'

target 'NVActivityIndicatorView_Example' do
  pod 'NVActivityIndicatorView-ObjC', :path => '../'

  target 'NVActivityIndicatorView_Tests' do
    inherit! :search_paths

    
  end
end
